{
 "title": "deep security",
 "tags": [
  "trendmicro",
  "workload-security"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "platform",
    "query": "label_values(deep_security_computers_total, platform)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(deep_security_modules_total, status)"
   },
   {
    "name": "type",
    "label": "type",
    "query": "label_values(deep_security_computers_total, type)"
   },
   {
    "name": "vul_type",
    "label": "vulnerabilities",
    "query": "label_values(deep_security_vulnerabilities_total, status)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"prevent\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "protected"
    },
    {
     "expr": "sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"detect\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"}) + on (metric) sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"discovered\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "exposed"
    }
   ]
  },
  {
   "title": "Vulnerabilities ($type)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(sum((deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=~\"[[type]]\"})) / on (metric) (sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=\"all\",type=~\"managed|unmanaged|critical|warning|unknown\"}))) * 100",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "Type ($type)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum((deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"prevent\",mode=\"all\",platform=~\"[[platform]]\",type=~\"[[type]]\"})) / on (metric) (sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=\"all\",type=~\"managed|unmanaged|critical|warning|unknown\"}))) * 100",
     "legendFormat": "protected"
    },
    {
     "expr": "(sum((deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"detect\",mode=\"all\",platform=~\"[[platform]]\",type=~\"[[type]]\"})) / on (metric) (sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=\"all\",type=~\"managed|unmanaged|critical|warning|unknown\"}))) * 100 +  on (metric) (sum((deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"discovered\",mode=\"all\",platform=~\"[[platform]]\",type=~\"[[type]]\"})) / on (metric) (sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=\"all\",type=~\"managed|unmanaged|critical|warning|unknown\"}))) * 100",
     "legendFormat": "exposed"
    }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"[[type]]\",status=\"all\",platform=~\"[[platform]]\"})",
     "legendFormat": "{{ $type }}"
    }
   ]
  },
  {
   "title": "% Exposed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "(sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"}) - on (metric) sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"prevent\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})) / on (metric) sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"}) * 100"
    }
   ]
  },
  {
   "title": "Vulnerabilities All Platforms ($type agents)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "deep_security_vulnerabilities_total{type=~\"[[type]]\",platform=\"all\",mode=\"all\",status!=\"all\"}",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum(deep_security_vulnerabilities_total{type=~\"[[type]]\",platform=\"all\",mode=\"all\",status!=\"all\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Vulnerabilities ($status agents)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "deep_security_vulnerabilities_total{type=~\"[[type]]\",platform=~\"[[platform]]\",mode=\"all\",status!=\"all\"}",
     "legendFormat": "{{ status }} {{ platform }} "
    }
   ]
  },
  {
   "title": "Vulnerabilities ($type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status!=\"all\",mode=\"all\",platform=\"all\",type=~\"[[type]]\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "% Exposed ($type)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "(sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=\"[[type]]\"}) - on (metric) sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"prevent\",mode=\"all\",platform=~\"[[platform]]\",type=\"[[type]]\"})) / on (metric) sum(deep_security_vulnerabilities_total{job=\"deep-security\",metric=\"ips_rules\",status=\"all\",mode=\"all\",platform=~\"[[platform]]\",type=\"[[type]]\"}) * 100"
    }
   ]
  },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Deep Security Deployment",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=\"managed\",status=\"all\",platform=\"all\"})",
     "legendFormat": "managed"
    },
    {
     "expr": "sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type!=\"managed\",status=\"all\",platform=\"all\"})",
     "legendFormat": "unmanaged"
    }
   ]
  },
  {
   "title": "Managed Hosts p/status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",status=\"all\",platform=\"all\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Vulnerabilities p/OS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deep_security_vulnerabilities_total{type=~\"managed|unmanaged|critical|warning|unknown\",platform=~\"linux\",mode=\"all\",status=\"all\"})",
     "legendFormat": "linux"
    },
    {
     "expr": "sum(deep_security_vulnerabilities_total{type=~\"managed|unmanaged|critical|warning|unknown\",platform=~\"windows\",mode=\"all\",status=\"all\"})",
     "legendFormat": "windows"
    },
    {
     "expr": "sum(deep_security_vulnerabilities_total{type=~\"managed|unmanaged|critical|warning|unknown\",platform=~\"unknown\",mode=\"all\",status=\"all\"})",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Vulnerabilities p/OS ($type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "deep_security_vulnerabilities_total{type=\"[[type]]\",platform=\"linux\",mode=\"all\",status=\"all\"}",
     "legendFormat": "linux"
    },
    {
     "expr": "deep_security_vulnerabilities_total{type=\"[[type]]\",platform=\"windows\",mode=\"all\",status=\"all\"}",
     "legendFormat": "windows"
    },
    {
     "expr": "deep_security_vulnerabilities_total{type=\"[[type]]\",platform=\"unknown\",mode=\"all\",status=\"all\"}",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Agent Version ($type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "deep_security_computers_total{type=\"[[type]]\",platform!=\"all\",status!=\"all\",metric=\"agent_version_major\"}",
     "legendFormat": "{{ status }} "
    }
   ]
  },
  {
   "title": "OS ($type agents)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "deep_security_computers_total{type=\"[[type]]\",platform!=\"all\",status=\"all\",metric=~\"os_type\"}",
     "legendFormat": "{{ platform }} "
    }
   ]
  },
  { "title": "Modules Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Modules Usage ($status agents)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"am_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "antimalware"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"wr_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "web reputation"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"fw_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "firewall"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"ip_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "ips"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"im_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "integrity monitor"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"li_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"managed|unmanaged|critical|warning|unknown\"})",
     "legendFormat": "log inspection"
    }
   ]
  },
  {
   "title": "Modules Usage ($type - $status agents)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"am_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "antimalware"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"wr_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "web reputation"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"fw_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "firewall"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"ip_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "ips"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"im_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "integrity monitor"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"li_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"})",
     "legendFormat": "log inspection"
    }
   ]
  },
  {
   "title": "Modules Usage ($type - $status agents)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"am_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "antimalware"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"wr_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "web reputation"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"fw_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "firewall"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"ip_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "ips"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"im_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "integrity monitor"
    },
    {
     "expr": "sum(deep_security_modules_total{job=\"deep-security\",metric=\"li_status\",status=\"on\",platform=~\"[[platform]]\",type=~\"[[type]]\"}) / on (metric) sum(deep_security_computers_total{job=\"deep-security\",metric=\"os_type\",type=~\"managed|unmanaged|warning|critical|unknown\",status=\"all\",platform=~\"[[platform]]\"}) * 100",
     "legendFormat": "log inspection"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Agent Version ($type)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "deep_security_computers_total{metric=\"agent_version_major\",type=\"[[type]]\",platform=~\"[[platform]]\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Agent Version ($type)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "targets": [
    {
     "expr": "deep_security_computers_total{metric=\"agent_version\",type=\"[[type]]\",platform=~\"[[platform]]\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}