# TRENDMICRO
# DEEP SECURITY
DS_HOST = "https://app.deepsecurity.trendmicro.com/api"
DS_API_KEY = ""
DS_VERIFY_SSL = True
DS_API_VERSION = "v1"
DS_API_CHECK = 3600 # in seconds

# HTTP_SERVER
SERVER_PORT = 9090

# LOGGING: NOTSET, INFO, WARN, DEBUG, ERROR, CRITICAL
LOG_LEVEL = "INFO"

